const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Adidas Fit Shirt",
      category: "Shirts",
      image: "/images/product-2.jpg",
      price: 180,
      countInStock: 20,
      brand: "Adidas",
      rating: 1.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Lacoste Slim Shirt",
      category: "Shirts",
      image: "/images/product-3.jpg",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 5.0,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/product-4.jpg",
      price: 78,
      countInStock: 15,
      brand: "Nike",
      rating: 3.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Puma Slim Pants",
      category: "Pants",
      image: "/images/product-5.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 2.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Adidas Fit Pants",
      category: "Pants",
      image: "/images/product-6.jpg",
      price: 150,
      countInStock: 12,
      brand: "Adidas",
      rating: 4,
      numReviews: 20,
      description: "high quality product",
    },
  ],
};

export default data;
